### ISSUE TITLE
I've been getting a variety of unexpected messages and errors over the past week.

### ISSUE THREAD

**Issue by Phylloxera** [StuntsPT/NCBI_Mass_Downloader#22] opened 2020-04-27 13:42 UTC
I'm downloading sequences from nucleotide
Here's query 1, last attempted early this morning:
```
"(complete[title] AND Viruses[Organism]) NOT wgs[PROP] NOT cellular organisms[ORGN] NOT AC_000001:AC_999999[PACC]"
```

And here are the last few lines of stderr:

```
  File "back_end.py", line 137 in main_organizer
  File "back_end.py", line 166 in re_downloader
  File "back_end.py", line 137 in main_organizer
  File "back_end.py", line 166 in re_downloader
In the end, 1225987 sequences were downloaded whereas 1224973 were expected.
```

Here's query 2, last attempted early this morning:

```
"("$startdate"[MDAT] : "$enddate"[MDAT] AND complete[title] AND Viruses[Organism]) NOT wgs[PROP] NOT cellular organisms[ORGN] NOT AC_000001:AC_999999[PACC]"
```
where `$startdate` is 2019/10/25 and `$enddate` is 2020/10/27. with a similar output to stderr. In the end, 95618 sequences were downloaded whereas 94604 were expected.

Here's query 3, last attempted early this morning:
```
"("$startdate"[PDAT] : "$enddate"[PDAT] AND complete[title] AND Viruses[Organism]) NOT wgs[PROP] NOT cellular organisms[ORGN] NOT AC_000001:AC_999999[PACC]"
```
with the same start and end dates. 86676 sequences were expected. But I got:

```
Failed to execute script NCBI_downloader
Traceback (most recent call last):
  File "NCBI_downloader.py", line 46, in <module>
  File "NCBI_downloader.py", line 42, in main
  File "back_end.py", line 258, in run_everything
  File "back_end.py", line 88, in main_organizer
```

I have received similar results to this in the past, but this is the longest they've persisted without eventually resolving.
I'm running the Linux binary inside a singularity container running the latest ubuntu LTS, "bionic"

Guessing there is a persistent entrez communication issue. Is there anything that can be tried?
Thanks, Aaron

**Comment by StuntsPT** [comment] 2020-04-27 14:41
Hi @Phylloxera .
I'll try to have a look at the issue later today. Since you have posted your queries I should have no problems reproducing the issue.

**Comment by StuntsPT** [comment] 2020-04-29 22:30
Hi again @Phylloxera,
I was unable to reproduce your issue, no matter what I tried. Nevertheless, your queries eneabled me to find a couple of bugs that *might* affect you. Please try to download the git branch `fork_mainteneance` and see if the code improves the situation for you.
I'll also update my fork of Biopython's Entrez with the new DTDs and that might also help. When I do that, I'll also release new binaries (you can just wait for the binaries if you are not confortable with running code from a different git branch!).
But if you do try the branch, please let me know if it solves the issue for you.

**Comment by Phylloxera** [comment] 2020-04-30 21:59
I just gave fork_maintenance a go with query 1 and python3 but no beans :(
Here are the last few lines of the error...

>   File "/home/aaron.dickey/NCBI_Mass_Downloader/Entrez.py", line 205, in efetch
>     return _open(cgi, variables, post=post)
>   File "/home/aaron.dickey/NCBI_Mass_Downloader/Entrez.py", line 604, in _open
>     handle = urlopen(cgi)
>   File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
>     response = meth(req, response)
>   File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
>     return self._call_chain(*args)
>   File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
>     result = func(*args)
>   File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 400: Bad Request

Did not run in from inside the singularity vm but attempted straight on our CENTOS7 server.
I'll give it another go in the morning.

**Comment by StuntsPT** [comment] 2020-04-30 22:51
Error 400 is even wierder. Can you please post the exact command line you have used? Thank you.

**Comment by Phylloxera** [comment] 2020-05-01 12:33
`python3 ~/NCBI_Mass_Downloader/NCBI_downloader.py -q "(complete[title] AND Viruses[Organism]) NOT wgs[PROP] NOT cellular organisms[ORGN] NOT AC_000001:AC_999999[PACC]" -d "nucleotide" -o m.fa`

I wonder if we're having some weird gov firewall issue... but no clue what to have sysadmin look for.

**Comment by StuntsPT** [comment] 2020-05-01 22:50
I still can't reproduce the issue (even with your latest query). All your queries are working just as expected on my end.
Do you have access to any system outside your eventual firewall? If you do, can you please try there?
I am, unfortunately, out of ideas. =-(

**Comment by Phylloxera** [comment] 2020-05-04 14:22
Oh no! I don't know if there will be value to me attempting on a personal system, but I'll try it on a few more systems inside our firewall. I'd hate to lose this great tool from my kit. Any advantage to reading in our sysadmin/it support on this issue?

**Comment by Phylloxera** [comment] 2020-05-05 18:39
I tried the above command but with the full path to NCBI_downloader.py from fork_maintenance this afternoon. This is what I got:

> Downloading record 1224001 to 1226555 of 1226555
> Checking for sequences that did not download... Please wait.
> 2 sequences did not download correctly (or at all). Retrying...
> Downloading record 1 to 2 of 2
> Checking for sequences that did not download... Please wait.
> 2 sequences did not download correctly (or at all). Retrying...
> Downloading record 1 to 2 of 2
> Checking for sequences that did not download... Please wait.
> 2 sequences did not download correctly (or at all). Retrying...
> Downloading record 1 to 2 of 2
> Checking for sequences that did not download... Please wait.
> 2 sequences did not download correctly (or at all). Retrying...
> Downloading record 1 to 2 of 2
> Checking for sequences that did not download... Please wait.
> 2 sequences did not download correctly (or at all). Retrying...
> Downloading record 1 to 2 of 2
> Checking for sequences that did not download... Please wait.
> NOTICE: After 5 retries, not all sequences were downloaded correctly.=-(
> A list of failed downloads can be found on m.fa.failed
> Program finished without error.

Interestingly, I caught the binary referenced in the original issue in the middle of a much longer

> 2 sequences did not download correctly (or at all). Retrying...
> Downloading record 1 to 2 of 2
> Checking for sequences that did not download... Please wait.

repeated string when attempted this morning.
`head m.fa.failed`
6T0V_R
6T0V_V
`grep "^>" m.fa | wc -l`
1226565
The extra 10 sequences when using fork_maintenance or >1014 sequences with the binary seem to be from the sequence redownload attempts.

**Comment by StuntsPT** [comment] 2020-05-05 18:45
Oh! Awesome! That means my new "failsafes" are working!
Those 2 sequences that "failed" have unmatching names between the FASTA record and the search result. That means that before the  `fork_maintenance` work, "NCBI Mass Sequence Downloader" would just continuously retry and never finish (I was not expecting such a mismatch to exist before).
Was this attempt performed from your personal machine, or from the same as before?

**Comment by Phylloxera** [comment] 2020-05-06 12:37
Same as before.

**Comment by Phylloxera** [comment] 2020-05-06 12:41
I wonder how long these mismatches persist inside ncbi's system... Like I said, I've seen this before and they eventually resolved to where the number of downloaded sequences == the number of query hits.

**Comment by StuntsPT** [comment] 2020-05-06 13:12
I don't think these mismatches persist for a very long time. It is the first time I have experienced one.
If this is finally working for you I will merge the branch to master, produce binaries and then close the issue.
The weird part is having had such a query eventually resolve. I'm not really sure how that could have happened before (maybe with a timeout? Or eventually following 5 API errors in quick succession?).

**Comment by Phylloxera** [comment] 2020-05-06 19:57
You can close it. I'm concerned that we're probably pushing 3 weeks with this mismatch, but I'll see who I can complain to at NCBI about that. NCBI_downloader is working as expected, but my workflow can't progress until the mismatch disappears.

**Comment by StuntsPT** [comment] 2020-05-06 23:01
Maybe try https://twitter.com/NCBI ? They are usually very quick to respond.

**Comment by Phylloxera** [comment] 2020-05-07 13:35
It looks like accessions called 6TOV_R and 6TOV_V exist, and they are showing up in broad searches like mine. But they download with the names pdb|6T0V|R and pdb|6T0V|V
I checked and this is true from their webserver too. Also, they are [not searchable](https://www.ncbi.nlm.nih.gov/nuccore/?term=6TOV_R) by name the way other accessions are.
I've submitted my issue via their normal help desk 48hour wait route because I do not want a twitter account. If you want to leave this issue open, I can post their answer here for continuity. It's up to you.

**Comment by StuntsPT** [comment] 2020-05-07 13:40
Thanks for taking the issue to NCBI. Feel free to reference them back here if need be. I'll leave the issue open.
My twitter suggestion was just in case you already had an account. Contacting NCBI staff is certainly no reason for creating an account there.
In the meantime I will release the new binaries. Thank you so much for reporting your issue, which really did help make *NCBI_Mass_Sequence_Downloader* a better program.

**Comment by Phylloxera** [comment] 2020-05-07 20:12
This is my correspondence with NCBI. It looks like their solution to the name mismatch is to be aware of it and parse accordingly. But it does not seem a simple | to _ conversion to me because of the preceding pdb| in the fasta header. Are there other NCBI databases where this issue could creep up?
I'm toying with the idea of modifying my query further to exclude very short sequences, which would solve it (at least for this query)

Dear Colleague,

It is a '0', not  an 'O', in those nucleotide accessions, '6T0V_R and 6T0V_V' in NCBI nucleotide database.

Both 6T0V_R and 6T0V_V are searchable: https://www.ncbi.nlm.nih.gov/nuccore/6T0V_R,6T0V_V

Since those nucleotide records are derived from the pdb record, the pdb accession is 6T0V.  If you want to match the nucleotide accession such as 6T0V_R with the pdb accession, 6T0V, for the chain R, you may try to add the chain name such as R to the pdb accession.

For the example of 6T0V_R,

https://www.ncbi.nlm.nih.gov/nuccore/1831503226

https://www.ncbi.nlm.nih.gov/nuccore/6T0V_R?report=fasta 
>pdb|6T0V|R Chain R, Bat Influenza A polymerase elongation complex with incoming UTP analogue (complete polymerase)
TATACCTCTGCTTCTGCTATT

the string, 6T0V|R, on the fasta definition line can be parsed out and converted to 6T0V_R for sequence name matches.


Here is another example,

https://www.ncbi.nlm.nih.gov/nuccore/4LW0_A

https://www.ncbi.nlm.nih.gov/nuccore/4LW0_A?report=fasta
  
>pdb|4LW0|A Chain A, Thf Riboswitch
NGAGAGTAGATGATTCGCGTTAAGTGTGTGTGAATGGGATGTCGTCACACAACGAAGCGAGAGCGCGGTG
AATCATTGCATCCGCTCCA


Best regards,

Hanguan Liu
NCBI User Services


****
* PLEASE DO NOT MODIFY THE SUBJECT LINE OF THIS EMAIL WHEN RESPONDING TO ENSURE CORRECT TRACKING *

Case Information:
Case #: CAS-532631-P0J3X1
Customer Name: Aaron Dickey
Customer Email: aaron.dickey@usda.gov
Case Created: 2020-05-07T13:28:11Z

Summary: accessions 6TOV_R and 6TOV_V in the nucleotide database

Details: Nucleotide/Nuccore Database

Hello,
The two accession numbers I've noted are not searchable by name the way other
accession numbers are. They also download from NCBI with a name mismatch. They download with names:
pdb|6T0V|V and pdb|6T0V|R respectively

This is problematic for  workflows that rely on NCBI expected/downloaded sequence name matches. See https://github.com/StuntsPT/NCBI_Mass_Downloader/issues/22

Thanks for your assistance,
Aaron

**Comment by StuntsPT** [comment] 2020-05-08 19:24
This was... unexpected. I'll try to wrap up some solution for this and report back.

**Comment by StuntsPT** [comment] 2020-05-09 03:02
This is truly messed up. I have to find a way to handle the mismatches *before* they are written onto the FASTA file.

**Comment by StuntsPT** [comment] 2020-05-09 23:18
Hi @Phylloxera, can you please try the `idtype` branch?
I have added a corner case for insane sequences like 6T0V_R/6T0V|R and 6T0V_V/6T0V|V.
I also finished some incomplete earlier work that reduces both memory usage and startup time. So I guess that's a win-win?
Let me know if it helps on your end.

**Comment by Phylloxera** [comment] 2020-05-13 18:52
the idtype branch downloaded 1231508 sequences as expected on May 13, 2020.
i got errors the first couple of attempts... different ones each time. I'm guessing right now it was maybe because i was trying to run in screen... or my default python3 is buggy... ghosts?
attempt 1:  ###Error 400
attempt 2: ###RuntimeError: Search Backend failed:
attempts 3&4: ###ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by StuntsPT** [comment] 2020-05-13 23:34
All those seem to be server side errors...
But that means it took you 5 attempts to get your file! owo!
I guess it's a good thing that I was able substantially decrease startup time.
Just out of curiosity, which version of python are you using?

**Comment by Phylloxera** [comment] 2020-05-14 13:42
3.7.3
I installed it a while back in anaconda2 and never bothered to figure out how to revert back to the version maintained by our sysadmin. I'm sure things will go better once I have everything running from the container again. Thanks for all your work on this!

**Comment by StuntsPT** [comment] 2020-05-14 13:44
Thank you, for your report!
I'll try to release the binaries this weekend, and leave the issue open until then. =-)

**Comment by StuntsPT** [comment] 2020-05-24 23:56
[New release is made](https://github.com/StuntsPT/NCBI_Mass_Downloader/releases/tag/v4.4).
Hopefully, everything is fine.
I'm closing this issue now. Feel free to request re-open should any further issues arise.
Also, thank you very much for helping improve *NCBI_Mass_Sequence_Downloader*. =-)

**Closed by StuntsPT** 2020-05-24 23:56 UTC
