### ISSUE TITLE
The program closes when I try to download a large dataset

### ISSUE THREAD

**Issue by enriiquee** [StuntsPT/NCBI_Mass_Downloader#18] opened 2018-05-16 08:32 UTC
Hello NCBI_Mass_Downloader. 

Firstly, thank you very much for this fantastic tool. Although, I tried to download the proteins of  Viridiplantae, using this Search Query:

Database to search: protein
"Viridiplantae"[Organism] OR Viridiplantae[All Fields]
File location: C:/Donwload/NCBIviridiplantae.fasta

When I click on Download, the program stops and closes.

**Comment by StuntsPT** [comment] 2018-05-16 09:10
Thank you for reporting this.
I will look into it and provide some feedback as soon as I can.

**Comment by StuntsPT** [comment] 2018-05-16 14:09
I have just released NCBI Mass Sequence Downloader v4.2.
In the [releases](https://github.com/StuntsPT/NCBI_Mass_Downloader/releases/tag/v4.2) page you will find the binaries for Windows, that should have the issue fixed.
Can you please try this new version and let me know if the problem is fixed?

**Comment by enriiquee** [comment] 2018-05-16 15:02
I tried to run but I have the same problem. 
Using the command l got this bug: 

> E:\Test_version\NCBI_Mass_Downloader-master>python NCBI_downloader.py
> Traceback (most recent call last):
>   File "E:\Test_version\NCBI_Mass_Downloader-master\back_end.py", line 248, in run_everything
>     rec = self.ncbi_search(self.database, self.term)
>   File "E:\Test_version\NCBI_Mass_Downloader-master\back_end.py", line 44, in ncbi_search
>     self.record = Entrez.read(self.handle)
>   File "E:\Test_version\NCBI_Mass_Downloader-master\Entrez.py", line 458, in read
>     record = handler.read(handle)
>   File "E:\Test_version\NCBI_Mass_Downloader-master\Parser.py", line 362, in read
>     self.parser.ParseFile(handle)
>   File "..\Modules\pyexpat.c", line 468, in EndElement
>   File "E:\Test_version\NCBI_Mass_Downloader-master\Parser.py", line 500, in endElementHandler
>     value = consumer.value
>   File "E:\Test_version\NCBI_Mass_Downloader-master\Parser.py", line 182, in value
>     raise RuntimeError(value)
> RuntimeError: Search Backend failed: std::bad_alloc

I also try with Homo Sapiens in order to discard that it is an error with the Viridiplantae database, but I get the same result.

**Comment by StuntsPT** [comment] 2018-05-16 15:32
Humm... this is indeed very odd.
But the error is different this time. I'll look into it.

**Comment by StuntsPT** [comment] 2018-05-17 14:08
I have narrowed down the problem to the use of `idtype="acc"`. Time to dive into the docs!

**Comment by StuntsPT** [comment] 2018-05-17 15:17
This seems to be an upstream problem... curl can trigger the error, like this:

```
curl https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi\?db\=nucleotide\&term\=viridiplantae\&retmax\=100000000\&idtype\=acc
```

**Comment by StuntsPT** [comment] 2018-05-17 15:40
I have just asked @NCBI for help, via twitter:
https://twitter.com/FPinaMartins/status/997139637310078978

I will look for a more formal way to report the issue.

**Comment by enriiquee** [comment] 2018-05-18 07:38
Perfect! 
Thank you very much and sorry for the inconveniences 👍

**Comment by StuntsPT** [comment] 2018-05-18 09:02
So, after emailing NCBI, it seems there is a limitation in getting data using "Accession numbers" instead of the deprecated GIs.
However, with the advice of the helpfull NCBI staff I was able to make a workaround, which should already be working in the `master` branch.
I will now build the binaries, which should be available soon.

**Comment by StuntsPT** [comment] 2018-05-18 15:47
I am also currently refactoring part of NCBI Mass Sequence Downloader to beter cope with the latest changes.
For starters, this new code starts the downloads much faster and consumes a lot less memory.
If you are comfortable with python and git, you may want to try the branch [idype](https://github.com/StuntsPT/NCBI_Mass_Downloader/tree/idtype), which should be useful for your particularly large download (since it is considerably faster).

**Comment by enriiquee** [comment] 2018-06-06 15:45
Dear 
Sorry for the delay in replying your message.
Still doesn't work, even the branch that you told me. I let the program running more than one day,  and the status bar has not even moved.

**Comment by StuntsPT** [comment] 2018-06-06 15:58
Hi again. This time the branch is working for me, 4/5 tries. But on one of them, something did stall somewhere, and I have to look into that.
This `idtype` branch is sort of a hack, so that less operations need to be performed, but is still not ideal. I'm working with NCBI staff to improve it, but they haven't answered my email in one week. I'll try to reach them again, but I want you to know that I did not drop the issue. =-)

**Comment by enriiquee** [comment] 2018-06-21 08:52
Perfect! Thank you so much.

**Comment by StuntsPT** [comment] 2020-05-09 23:42
Hi @enriiquee .
I know it's been a while (almost two years), but I've been doing some maintenance. Your use-case is now officially working on my end using the branch `idtype`.
Can you please let me know if things are working for you too?

Also, sorry about the delay. =-)

**Comment by StuntsPT** [comment] 2020-05-24 23:57
There is a [new release](https://github.com/StuntsPT/NCBI_Mass_Downloader/releases/tag/v4.4) that should address this problem.
I'm closing this issue. Let me know if you need a re-open.

**Closed by StuntsPT** 2020-05-24 23:57 UTC
Labels: bug, server side
