### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by ChongLC** [StuntsPT/NCBI_Mass_Downloader#23] opened 2021-03-27 23:39 UTC
Dear developer, 

I faced HTTP error while downloading a very large protein sequence dataset. May I know how to encounter this issue?

Looking forward to hearing from you. 

Thank you.

**Comment by StuntsPT** [comment] 2021-03-28 00:55
Hi @ChongLC 
Can you please provide a minimal example on how to trigger the error?
Thank you.

**Comment by ChongLC** [comment] 2021-03-28 04:11
Dear StuntsPT/NCBI_Mass_Downloader,

I tried this for downloading entire virus dataset from NCBI and trigger
this error.

Looking forward to hearing from you.

Best regards,
CHONG

**Comment by StuntsPT** [comment] 2021-03-29 16:43
Dear @ChongLC,
I am attempting to reproduce your issue, but it might take a while (currently at 1.6M sequences downloaded), since the `HTTP Error 400` is frequently due to connection issues . In the meantime, keep in mind that if you use the same output filename twice, *NCBI_Mass_Downloader* will attempt to continue where it left off. Eg. if a download was interrupted during sequence number 3897654, and you try the same command again, *NCBI_Mass_Sequence_Downloader* will attempt to resume the download from sequence 3897655 (although it might take a while to restart downloading!).
Hope this helps, but I should report back soon.

**Comment by ChongLC** [comment] 2021-03-29 16:47
Dear developer, 

Okay. Let me try it and get back to you as well. Thank you very much!

**Comment by ChongLC** [comment] 2021-03-30 18:36
Dear developer, 

While rerunning the code after the error 400, it seems like redownloading from the start, instead of resuming the download. Currently, my download file consists of ~8.77M sequences, yet it still continues running. As there is only ~8.4M sequences in NCBI Entrez Protein Database. Hence, I doubt the downloading. And yeah, while checking for the same sequences (duplicates) based on fasta header, there are about ~4.26M sequences.

**Comment by StuntsPT** [comment] 2021-03-31 01:33
I have found the bug and am working on solving it.
Expect news soon.

**Comment by ChongLC** [comment] 2021-03-31 07:09
Thank you and looking forwards to the solution!

**Comment by StuntsPT** [comment] 2021-04-01 02:29
@ChongLC I think I have fixed the problem.
It's not 100% tested yet, but you can try the `ng` branch, which should be able to resume the downloads.
It requires a new dependency, though - `requests`. You can install it via `pip3 install requests` if it's not already installed.
I need to do some clean-ups, and then I will be able to make a proper release.

**Comment by StuntsPT** [comment] 2021-04-01 18:56
Ok, so this is much harder than I anticipated.
Apparently there is a bug in NCBI which make it return an error when fetching some (but not all) protein sequences using efetch:
https://www.biostars.org/p/476638/
There is not much I can do from this side to solve it.
I'd say your best bet is to use the largest file you have, and attempt to "complete" that download. If there are few sequences left, there is a good chance you won't be hitting one that triggers the bug.

**Comment by StuntsPT** [comment] 2021-04-02 00:05
I may have found a work-around.
This will actually make the whole approach more elegant...! I'll get back to you soon.

**Comment by ChongLC** [comment] 2021-04-03 22:16
Great to hear that. Looking forward to hearing from you on the update.

**Comment by StuntsPT** [comment] 2021-04-05 16:48
@ChongLC ,
The reason this is not yet working is due to a likely bug in NCBI's servers. I have contacted support and we are now in email contact to try to solve it. But at this point it is somewhat out of my hands...

**Comment by StuntsPT** [comment] 2021-04-11 01:47
@ChongLC ,
I have confirmed the problem with NCBI's team. Although the bug has not been solved (an unexpected timeout on their servers when using epost), together we were able to devise a work-around, that should function just as well.
I have now implemented this solution in the branch `ng`. It has been tested with a smaller dataset than yours and is working just as expected.
I still want to implement a performance enhancing mechanism before I make a new release (by using cached accession numbers), so I will not release a new version just yet, but you can use the new branch to make your download (or continue an incomplete one).
Please let me know if you encounter any further issues.
I will close this issue once you confirm your problem was solved with the `ng`branch.

**Comment by ChongLC** [comment] 2021-04-11 13:49
Dear Developer, 

Thank you for your message. I will try from my side, however, will not be so soon as rushing for manuscript correction. Sorry. Definitely, I will update you once I try from my side. Thank you. 

BR, 
Chong

**Comment by StuntsPT** [comment] 2021-04-21 01:19
Hi @ChongLC ,
I'm sorry, github has inadvertently closed the issue based on a commit message.
I'm just letting you know that a new release is done. It now uses threading, which allows for downloading files in parallel.
This has drastically reduced the download time (your query used to take 3 days on my machines, now it takes "only" 7 hours).
On another note, in this particular query, some of the accession numbers are mismatched between the FASTA file and record number in the database, which means that download verification will always fail. To work around it I have added a new option: `-nv`which disables accession number verification (and also disables the ability to resume an interrupted download).
However, in this new version, it is much less likely that a download is interrupted, so you should be OK using it.
The command I'd recommend using is this:

```bash
python3 NCBI_downloader.py  -q "txid10239[Organism:exp]" -d "protein" -nv -o allVirus2803.fasta
```
Also, you probably don't want conceptual 3D protein structures in your FASTA, so I'd recommend slightly changing the query:

```bash
python3 NCBI_downloader.py  -q "txid10239[Organism:exp] NOT protein_structure[sb]" -d "protein" -nv -o allVirus2803_no_PDB.fasta
```

Best,
Francisco

**Comment by ChongLC** [comment] 2021-04-21 18:49
Dear developer,

Owh that's nice. Unfortunately, I still have no time to test this out. I
will try to allocate some time by next week or next two weeks. I will get
back to you soon after I tested that. Thank you for your message.

Best regards,
*CHONG* LI CHUIN

**Comment by ChongLC** [comment] 2021-05-09 05:39
Dear developer, 

Sorry for the late reply. I have tried running it. The result looks fine and fast. May I know what function you have added to make it download the sequence so fast?

Thank you. 

Best regards, 
Chong Li Chuin

**Comment by StuntsPT** [comment] 2021-05-09 21:11
Dear @ChongLC , 

>Sorry for the late reply. I have tried running it. The result looks fine and fast.

Thank you for your feedback.

>May I know what function you have added to make it download the sequence so fast?

I have implemented threading. That means the sequences are being downloaded in up to 8 parallel batches.
I figured that connection speed was not the bottleneck when downloading, but rather waiting for NCBI's servers responses. Implementing threading allowed a large mitigation of this bottleneck, without much (hardly any) impact on individual batches download speed.
I don't know why I didn't think of this earlier.
Anyway, your feedback was much appreciated, and was the push I needed to make a lot of necessary changes, so thank you for your participation!
Furthermore, your query was causing some strange issues, that turned out to be server side NCBI bugs (3 separate bugs, in fact!), that eneded up being solved there too. So this was an all-round win.

I'm closing the issue, since everything seems solved.

And, please, if this tool was useful for your research do not forget to cite [our paper](https://doi.org/10.1016/j.softx.2016.04.007), since it's really the only way to get funding for maintenance! 🙏

**Closed by StuntsPT** 2021-05-09 21:11 UTC

**Comment by ChongLC** [comment] 2021-05-10 04:26
Dear developer,

Thank you again that this tool helps me a lot. And definitely, we will cite
your paper during paper preparation.

Best regards,
*CHONG* LI CHUIN
