### ISSUE TITLE
Windows executable does not work

### ISSUE THREAD

**Issue by renzok** [StuntsPT/NCBI_Mass_Downloader#7] opened 2016-02-09 23:28 UTC
I downloaded [latest release](https://github.com/StuntsPT/NCBI_Mass_Downloader/tree/v2.8) and started the pre-build windows executable.

I was simply not able to start any download using the Windows executable on a windows 7 machine. Whatever parameters in whatever combination I entered in the gui-form, the program gave an error message that the email might be wrong and claimed to start downloading, but never did and instead is stalled.

**Comment by StuntsPT** [comment] 2016-02-10 10:50
Humm...
I have tested the windows build on several machines and that never happened to me.
Can you please share what parameters you were using? That could be a bug in the email verification function.
Also, can you reproduce in the "source" version, or just the binary?

Thank you for reporting this.

**Comment by renzok** [comment] 2016-02-11 23:26
Indeed, it is a bug in the email verification. However, now that there is issue #13 with not passing users email to Entrez, I can neither fix the issue in master branch, nor can I disclose the valid email that was revealing the bug for you to fix it.

**Comment by StuntsPT** [comment] 2016-02-12 13:33
So, I take it the v3.1 binary is working fine?

**Comment by StuntsPT** [comment] 2017-01-16 15:48
Closing, since it's been a while and a few new versions have been released.

**Closed by StuntsPT** 2017-01-16 15:48 UTC
Labels: bug
